/*
  根据判断结果自动生成添加分区的语句
*/


CREATE OR REPLACE PROCEDURE P_ADD_PARTITION (P_TABLENAME VARCHAR2,
  P_TYPE VARCHAR2 DEFAULT 'D',
  P_DATE DATE DEFAULT TRUNC(ADD_MONTHS(SYSDATE, 1), 'MM')) AS
  BEGIN
    IF P_TYPE = 'D' THEN
      FOR I IN (SELECT TO_CHAR(P_DATE + ROWNUM - 1, 'YYYYMMDD') DAY,
      TO_CHAR(P_DATE + ROWNUM, 'YYYYMMDD') TOMORROW
      FROM DUAL
      CONNECT BY P_DATE + ROWNUM - 1 < ADD_MONTHS(P_DATE, 1)) LOOP
      dbms_output.put_line( 'ALTER TABLE ' || P_TABLENAME || ' SPLIT PARTITION P_MAX AT ('''
      || I.TOMORROW || ''') INTO (PARTITION P' || I.DAY || ', PARTITION P_MAX)');
    END LOOP;
  ELSE
    dbms_output.put_line( 'ALTER TABLE ' || P_TABLENAME || ' SPLIT PARTITION P_MAX AT ('''
    || TO_CHAR(ADD_MONTHS(P_DATE, 1), 'YYYYMM') || ''') INTO (PARTITION P'
    || TO_CHAR(P_DATE, 'YYYYMM') || ', PARTITION P_MAX)');
  END IF;
END;
/
