set long 10000
set longchunksize 1000
set serveroutput on size 999999
set linesize 150

variable  MY_TASK_NAME VARCHAR2(30);

BEGIN
  :MY_TASK_NAME := DBMS_SQLTUNE.CREATE_TUNING_TASK('&sql_id',NULL,'COMPREHENSIVE',60,'sqltuning_zq_' ||TO_CHAR(SYSDATE,'yyyymmddhh24miss'),'SQL TUNING ADVISOR BY ZHANGQIAOC');
  DBMS_OUTPUT.PUT_LINE(:MY_TASK_NAME);
  DBMS_SQLTUNE.EXECUTE_TUNING_TASK(:MY_TASK_NAME);
END;
/

SELECT DBMS_SQLTUNE.REPORT_TUNING_TASK(:MY_TASK_NAME) FROM DUAL;

