set linesize 130
set pagesize 9999
set feedback off

--检查后台进程等待事件，注意一些不正常的等待事件
col event for a30
SELECT event,total_waits,total_timeouts,time_waited,average_wait
  FROM (SELECT ROWNUM RN, A.*
	  FROM V$SESSION_EVENT A
	 WHERE SID IN (SELECT SID FROM V$SESSION WHERE TYPE = 'BACKGROUND'
	   AND EVENT NOT IN(SELECT EVENT FROM perfstat.stats$idle_event))
	 ORDER BY TIME_WAITED DESC)
 WHERE ROWNUM < 10;
 
--检查硬解析
SELECT PLAN_HASH_VALUE, COU
  FROM (SELECT PLAN_HASH_VALUE, COU, ROWNUM RN
	  FROM (SELECT PLAN_HASH_VALUE, COUNT(*) COU
		  FROM V$SQL
		 WHERE PLAN_HASH_VALUE > 0
		 GROUP BY PLAN_HASH_VALUE
		 ORDER BY 2 DESC))
 WHERE RN <= 5;

--未分析和长时间不分析的对象
SELECT OWNER,TYPE,COUNT(*) FROM( 
SELECT owner,table_name,NULL partition_name,last_analyzed,'TABLE' TYPE FROM dba_tables WHERE owner NOT IN ('SYS','SYSTEM','OUTLN','DBSNMP','WMSYS')AND ( LAST_ANALYZED < SYSDATE - 50 OR LAST_ANALYZED IS NULL)
UNION ALL
SELECT table_owner,table_name,partition_name,last_analyzed,'TABLE PARTITION' TYPE FROM dba_tab_partitions WHERE table_owner NOT IN ('SYS','SYSTEM','OUTLN','DBSNMP','WMSYS') AND ( LAST_ANALYZED < SYSDATE - 50 OR LAST_ANALYZED IS NULL)
UNION ALL
SELECT owner,INDEX_NAME,NULL partition_name,last_analyzed,'INDEX' TYPE FROM DBA_INDEXES WHERE owner NOT IN ('SYS','SYSTEM','OUTLN','DBSNMP','WMSYS')AND ( LAST_ANALYZED < SYSDATE - 50 OR LAST_ANALYZED IS NULL)
UNION ALL
SELECT INDEX_OWNER,INDEX_NAME,PARTITION_NAME,LAST_ANALYZED,'INDEX PARTITION' TYPE FROM DBA_IND_PARTITIONS WHERE INDEX_OWNER NOT IN ('SYS','SYSTEM','OUTLN','DBSNMP','WMSYS')AND ( LAST_ANALYZED < SYSDATE - 50 OR LAST_ANALYZED IS NULL)
) GROUP BY OWNER,TYPE ORDER BY 3 DESC;

--需要KEEP的对象
col owner for a30
col object_name for a30
SELECT AA.OWNER, AA.OBJECT_NAME, C.BYTES / 1024 / 1024 MB, TOUCH_COU
  FROM (SELECT B.OWNER, B.OBJECT_NAME, COUNT(A.TCH) TOUCH_COU
	  FROM X$BH A, DBA_OBJECTS B
	 WHERE A.OBJ = B.DATA_OBJECT_ID
	 GROUP BY B.OWNER, B.OBJECT_NAME) AA,
       DBA_SEGMENTS C
 WHERE AA.OWNER = C.OWNER
   AND AA.OBJECT_NAME = C.SEGMENT_NAME
   AND C.BYTES / 1024 / 1024 <=1024  
   AND AA.OWNER NOT IN ('SYS','SYSTEM','OUTLN','DBSNMP','WMSYS')
   ORDER BY touch_cou DESC;

--需要keep的shared_pool对象
col name for a50
SELECT OWNER, NAME, SHARABLE_MEM, KEPT
  FROM V$DB_OBJECT_CACHE
 WHERE SHARABLE_MEM > 102400
   AND KEPT = 'NO'
   AND UPPER(SUBSTR(NAME, 1, 20)) NOT LIKE 'SELECT %'
 ORDER BY SHARABLE_MEM DESC;

--ROW CACHE对象MISS率
SELECT PARAMETER,
       COUNT(GETS) GETS,
       COUNT(GETMISSES) GETMISSES,
       COUNT(GETMISSES) / COUNT(GETS) MISS_RATIO
  FROM V$ROWCACHE
 GROUP BY PARAMETER
HAVING COUNT(GETMISSES) / COUNT(GETS) > 0.1
 ORDER BY 4;

--ITL等待
SELECT OWNER,
       OBJECT_NAME,
       SUBOBJECT_NAME,
       OBJECT_TYPE,
       STATISTIC_NAME,
       VALUE
  FROM V$SEGMENT_STATISTICS
 WHERE STATISTIC_NAME = 'ITL waits'
   AND VALUE > 100
 ORDER BY VALUE DESC;
--ROW LOCK
SELECT OWNER,
       OBJECT_NAME,
       SUBOBJECT_NAME,
       OBJECT_TYPE,
       STATISTIC_NAME,
       VALUE
  FROM V$SEGMENT_STATISTICS
 WHERE STATISTIC_NAME = 'row lock waits'
   AND VALUE > 100
 ORDER BY VALUE DESC;

--比较大的索引
SELECT OWNER,SEGMENT_NAME INDEX_NAME,MB INDEX_MB,TABLE_OWNER,TABLE_NAME,TABLE_MB
  FROM (SELECT OWNER,SEGMENT_NAME,MB,TABLE_OWNER,TABLE_NAME,RN,COU,TYPE,
     	       LAG(MB, RN - 1, 0) OVER(PARTITION BY TABLE_OWNER, TABLE_NAME ORDER BY RN) TABLE_MB
	  FROM (SELECT OWNER,SEGMENT_NAME,MB,TABLE_OWNER,TABLE_NAME,TYPE,
	               ROW_NUMBER() OVER(PARTITION BY TABLE_OWNER, TABLE_NAME ORDER BY TYPE DESC) RN,
                       COUNT(*) OVER(PARTITION BY TABLE_OWNER, TABLE_NAME) COU
                  FROM (SELECT OWNER,SEGMENT_NAME,MB,NVL(TABLE_OWNER, OWNER) TABLE_OWNER,NVL(TABLE_NAME, SEGMENT_NAME) TABLE_NAME,NVL2(TABLE_NAME, 'INDEX', 'TABLE') TYPE
                          FROM (SELECT AA.*, BB.TABLE_OWNER, BB.TABLE_NAME
                                  FROM (SELECT A.OWNER,
                                               A.SEGMENT_NAME,
                                               SUM(BYTES / 1024 / 1024) MB
                                          FROM DBA_SEGMENTS A
                                        -- WHERE OWNER = 'QYW'
                                         WHERE OWNER NOT IN('SYS','SYSTEM','MONITOR','ETL','FILEDB','MGMT_VIEW','OUTLN','DBSNMP','WMSYS','EXFSYS','SYSMAN','TSMSYS','DIP')
                                         GROUP BY A.OWNER, A.SEGMENT_NAME) AA,
                                       DBA_INDEXES BB
                                 WHERE AA.SEGMENT_NAME = BB.INDEX_NAME(+)) AAA)))
 WHERE COU > 1 AND RN > 1 AND TABLE_MB>100 AND MB/TABLE_MB > 0.5;


exit;

