-- drop PUBLIC DATABASE LINK TEST_COMPARE;
--  CREATE PUBLIC DATABASE LINK TEST_COMPARE CONNECT TO enmo IDENTIFIED BY enmo USING '(DESCRIPTION
--     =
--         (ADDRESS_LIST =
--         (ADDRESS = (PROTOCOL = TCP)(HOST = 135.32.9.139)(PORT = 1521))
--         )
--         (CONNECT_DATA =
--            (SERVICE_NAME=ibsscrm)
--         )
-- )';

PROMPT 开始检查数据库对象 ...
COL CACHE_SIZE FOR 9,999
COL COLUMN_NAME FOR A30
COL CONSTRAINT_TYPE FOR A3
COL DATA_TYPE FOR A12
COL OBJECT_NAME FOR A30
COL OWNER FOR A18
COL O_CNT FOR 999,999
COL O_LAST FOR 999,999,999,999,999
COL O_NAME FOR A30
COL PO_DIFF FOR 999,999
COL P_CNT FOR 999,999
COL P_LAST FOR 999,999,999,999,999
COL P_NAME FOR A30
COL TABLE_NAME FOR A30
COL DATA_DEFAULT FOR A50
COL DB_LINK FOR A33
SET LINES 222 PAGES 11111
!mv checkResult.txt checkResult_`date +"%Y%m%d_%H%M%S"`.txt
spo checkResult.txt

PROMPT ====================================================
PROMPT 1. 检查数据库Sequence对象 ...
PROMPT ====================================================
PROMPT --> 1.1. 对比Sequence对象数量
PROMPT    -------------------------------------------------

SELECT OWNER, MAX(P_CNT) P_CNT, MAX(O_CNT) O_CNT, MAX(P_CNT) - MAX(O_CNT) PO_DIFF
  FROM (SELECT SEQUENCE_OWNER OWNER, COUNT(*) P_CNT, 0 O_CNT FROM DBA_SEQUENCES GROUP BY SEQUENCE_OWNER
         UNION ALL
        SELECT SEQUENCE_OWNER, 0, COUNT(*) FROM DBA_SEQUENCES@TEST_COMPARE GROUP BY SEQUENCE_OWNER) S
 WHERE S.OWNER NOT IN ('DBMON','GOLDENGATE','PRECISE2','PRECISE1','SPATIAL_WFS_ADMIN_USR','DIP','MDDATA','ORACLE_OCM'
                      ,'SPATIAL_CSW_ADMIN_USR','XS$NULL','SCOTT','DBSNMP','SPA','OLAPSYS','ORDPLUGINS','XDB','SYSMAN'
                      ,'APPQOSSYS','DMSYS','EXFSYS','ORDSYS','SI_INFORMTN_SCHEMA','ANONYMOUS','CTXSYS','ORDDATA','WMSYS'
                      ,'MDSYS','SYSTEM','MGMT_VIEW','SYS','PUBLIC','OUTLN','TSMSYS','DSG','PERFSTAT','IGNITE_M')
 GROUP BY OWNER
HAVING MAX(P_CNT) <> MAX(O_CNT)
 ORDER BY PO_DIFF;

PROMPT --> 1.2. 列出生产库中Last Number大于新库的所有Sequence
PROMPT    -------------------------------------------------

SELECT P.SEQUENCE_OWNER OWNER, P.SEQUENCE_NAME P_NAME, P.LAST_NUMBER P_LAST, O.LAST_NUMBER O_LAST
  FROM DBA_SEQUENCES P, DBA_SEQUENCES@TEST_COMPARE O
 WHERE P.SEQUENCE_OWNER = O.SEQUENCE_OWNER
   AND P.SEQUENCE_NAME = O.SEQUENCE_NAME
   AND P.LAST_NUMBER > O.LAST_NUMBER
   AND P.SEQUENCE_OWNER NOT IN ('DBMON','GOLDENGATE','PRECISE2','PRECISE1','SPATIAL_WFS_ADMIN_USR','DIP','MDDATA'
                               ,'ORACLE_OCM','SPATIAL_CSW_ADMIN_USR','XS$NULL','SCOTT','DBSNMP','SPA','OLAPSYS'
                               ,'ORDPLUGINS','XDB','SYSMAN','APPQOSSYS','DMSYS','EXFSYS','ORDSYS','SI_INFORMTN_SCHEMA'
                               ,'ANONYMOUS','CTXSYS','ORDDATA','WMSYS','MDSYS','SYSTEM','MGMT_VIEW','SYS','PUBLIC'
                               ,'OUTLN','TSMSYS','DSG','PERFSTAT','IGNITE_M');

PROMPT ====================================================
PROMPT 2. 检查数据库对象 ...
PROMPT ====================================================
PROMPT --> 2.1. 对比对象数量

SELECT OWNER, OBJECT_TYPE P_TYPE, MAX(P_CNT) P_CNT, MAX(O_CNT) O_CNT, MAX(P_CNT) - MAX(O_CNT) PO_DIFF
  FROM (SELECT OWNER, OBJECT_TYPE, COUNT(*) P_CNT, 0 O_CNT
          FROM DBA_OBJECTS
         WHERE OBJECT_NAME NOT LIKE 'BIN%'
           AND OBJECT_NAME NOT LIKE 'SYS_%'
         GROUP BY OWNER, OBJECT_TYPE
         UNION ALL
        SELECT OWNER, OBJECT_TYPE, 0, COUNT(*)
          FROM DBA_OBJECTS@TEST_COMPARE
         WHERE OBJECT_NAME NOT LIKE 'BIN%'
           AND OBJECT_NAME NOT LIKE 'SYS_%'
         GROUP BY OWNER, OBJECT_TYPE) O
 WHERE O.OWNER NOT IN ('DBMON','GOLDENGATE','PRECISE2','PRECISE1','SPATIAL_WFS_ADMIN_USR','DIP','MDDATA','ORACLE_OCM'
                      ,'SPATIAL_CSW_ADMIN_USR','XS$NULL','SCOTT','DBSNMP','SPA','OLAPSYS','ORDPLUGINS','XDB','SYSMAN'
                      ,'APPQOSSYS','DMSYS','EXFSYS','ORDSYS','SI_INFORMTN_SCHEMA','ANONYMOUS','CTXSYS','ORDDATA'
                      ,'WMSYS','MDSYS','SYSTEM','MGMT_VIEW','SYS','PUBLIC','OUTLN','TSMSYS','DSG','PERFSTAT','IGNITE_M')
 GROUP BY OWNER, OBJECT_TYPE
HAVING MAX(P_CNT) <> MAX(O_CNT)
 ORDER BY PO_DIFF;


  select owner,object_name,object_type  from dba_objects@TEST_COMPARE where owner NOT IN ('DBMON','GOLDENGATE','PRECISE2','PRECISE1','SPATIAL_WFS_ADMIN_USR','DIP','MDDATA','ORACLE_OCM'
                      ,'SPATIAL_CSW_ADMIN_USR','XS$NULL','SCOTT','DBSNMP','SPA','OLAPSYS','ORDPLUGINS','XDB','SYSMAN'
                      ,'APPQOSSYS','DMSYS','EXFSYS','ORDSYS','SI_INFORMTN_SCHEMA','ANONYMOUS','CTXSYS','ORDDATA'
                      ,'WMSYS','MDSYS','SYSTEM','MGMT_VIEW','SYS','PUBLIC','OUTLN','TSMSYS','DSG','PERFSTAT','IGNITE_M') and STATUS='VALID'
  minus
  select owner,object_name,object_type  from dba_objects where owner NOT IN ('DBMON','GOLDENGATE','PRECISE2','PRECISE1','SPATIAL_WFS_ADMIN_USR','DIP','MDDATA','ORACLE_OCM'
                      ,'SPATIAL_CSW_ADMIN_USR','XS$NULL','SCOTT','DBSNMP','SPA','OLAPSYS','ORDPLUGINS','XDB','SYSMAN'
                      ,'APPQOSSYS','DMSYS','EXFSYS','ORDSYS','SI_INFORMTN_SCHEMA','ANONYMOUS','CTXSYS','ORDDATA'
                      ,'WMSYS','MDSYS','SYSTEM','MGMT_VIEW','SYS','PUBLIC','OUTLN','TSMSYS','DSG','PERFSTAT','IGNITE_M') and STATUS='VALID';


PROMPT --> 2.2. 列出生产库中比新库中多的对象
PROMPT    -------------------------------------------------

SELECT OWNER, OBJECT_NAME, OBJECT_TYPE
  FROM DBA_OBJECTS
 WHERE OBJECT_NAME NOT LIKE 'BIN%'
   AND OBJECT_NAME NOT LIKE 'SYS_%'
   AND OWNER NOT IN ('DBMON','GOLDENGATE','PRECISE2','PRECISE1','SPATIAL_WFS_ADMIN_USR','DIP','MDDATA','ORACLE_OCM'
                    ,'SPATIAL_CSW_ADMIN_USR','XS$NULL','SCOTT','DBSNMP','SPA','OLAPSYS','ORDPLUGINS','XDB','SYSMAN'
                    ,'APPQOSSYS','DMSYS','EXFSYS','ORDSYS','SI_INFORMTN_SCHEMA','ANONYMOUS','CTXSYS','ORDDATA'
                    ,'WMSYS','MDSYS','SYSTEM','MGMT_VIEW','SYS','PUBLIC','OUTLN','TSMSYS','DSG','PERFSTAT','IGNITE_M')
MINUS
SELECT OWNER, OBJECT_NAME, OBJECT_TYPE
  FROM DBA_OBJECTS@TEST_COMPARE
 WHERE OBJECT_NAME NOT LIKE 'BIN%'
   AND OBJECT_NAME NOT LIKE 'SYS_%'
   AND OWNER NOT IN ('DBMON','GOLDENGATE','PRECISE2','PRECISE1','SPATIAL_WFS_ADMIN_USR','DIP','MDDATA','ORACLE_OCM'
                    ,'SPATIAL_CSW_ADMIN_USR','XS$NULL','SCOTT','DBSNMP','SPA','OLAPSYS','ORDPLUGINS','XDB','SYSMAN'
                    ,'APPQOSSYS','DMSYS','EXFSYS','ORDSYS','SI_INFORMTN_SCHEMA','ANONYMOUS','CTXSYS','ORDDATA'
                    ,'WMSYS','MDSYS','SYSTEM','MGMT_VIEW','SYS','PUBLIC','OUTLN','TSMSYS','DSG','PERFSTAT','IGNITE_M');

PROMPT --> 2.3. 列出新库中比生产库中多的对象
PROMPT    -------------------------------------------------

SELECT OWNER, OBJECT_NAME, OBJECT_TYPE
  FROM DBA_OBJECTS@TEST_COMPARE
 WHERE OBJECT_NAME NOT LIKE 'BIN%'
   AND OBJECT_NAME NOT LIKE 'SYS_%'
   AND OWNER NOT IN ('DBMON','GOLDENGATE','PRECISE2','PRECISE1','SPATIAL_WFS_ADMIN_USR','DIP','MDDATA','ORACLE_OCM'
                    ,'SPATIAL_CSW_ADMIN_USR','XS$NULL','SCOTT','DBSNMP','SPA','OLAPSYS','ORDPLUGINS','XDB','SYSMAN'
                    ,'APPQOSSYS','DMSYS','EXFSYS','ORDSYS','SI_INFORMTN_SCHEMA','ANONYMOUS','CTXSYS','ORDDATA'
                    ,'WMSYS','MDSYS','SYSTEM','MGMT_VIEW','SYS','PUBLIC','OUTLN','TSMSYS','DSG','PERFSTAT','IGNITE_M')
MINUS
SELECT OWNER, OBJECT_NAME, OBJECT_TYPE
  FROM DBA_OBJECTS
 WHERE OBJECT_NAME NOT LIKE 'BIN%'
   AND OBJECT_NAME NOT LIKE 'SYS_%'
   AND OWNER NOT IN ('DBMON','GOLDENGATE','PRECISE2','PRECISE1','SPATIAL_WFS_ADMIN_USR','DIP','MDDATA','ORACLE_OCM'
                    ,'SPATIAL_CSW_ADMIN_USR','XS$NULL','SCOTT','DBSNMP','SPA','OLAPSYS','ORDPLUGINS','XDB','SYSMAN'
                    ,'APPQOSSYS','DMSYS','EXFSYS','ORDSYS','SI_INFORMTN_SCHEMA','ANONYMOUS','CTXSYS','ORDDATA'
                    ,'WMSYS','MDSYS','SYSTEM','MGMT_VIEW','SYS','PUBLIC','OUTLN','TSMSYS','DSG','PERFSTAT','IGNITE_M');

PROMPT --> 2.4. 列出源库有效而新库失效对象
PROMPT    -------------------------------------------------
  select owner,object_name,object_type  from dba_objects@TEST_COMPARE where owner NOT IN ('DBMON','GOLDENGATE','PRECISE2','PRECISE1','SPATIAL_WFS_ADMIN_USR','DIP','MDDATA','ORACLE_OCM'
                      ,'SPATIAL_CSW_ADMIN_USR','XS$NULL','SCOTT','DBSNMP','SPA','OLAPSYS','ORDPLUGINS','XDB','SYSMAN'
                      ,'APPQOSSYS','DMSYS','EXFSYS','ORDSYS','SI_INFORMTN_SCHEMA','ANONYMOUS','CTXSYS','ORDDATA'
                      ,'WMSYS','MDSYS','SYSTEM','MGMT_VIEW','SYS','PUBLIC','OUTLN','TSMSYS','DSG','PERFSTAT','IGNITE_M') and STATUS='VALID'
  minus
  select owner,object_name,object_type  from dba_objects where owner NOT IN ('DBMON','GOLDENGATE','PRECISE2','PRECISE1','SPATIAL_WFS_ADMIN_USR','DIP','MDDATA','ORACLE_OCM'
                      ,'SPATIAL_CSW_ADMIN_USR','XS$NULL','SCOTT','DBSNMP','SPA','OLAPSYS','ORDPLUGINS','XDB','SYSMAN'
                      ,'APPQOSSYS','DMSYS','EXFSYS','ORDSYS','SI_INFORMTN_SCHEMA','ANONYMOUS','CTXSYS','ORDDATA'
                      ,'WMSYS','MDSYS','SYSTEM','MGMT_VIEW','SYS','PUBLIC','OUTLN','TSMSYS','DSG','PERFSTAT','IGNITE_M') and STATUS='VALID';


PROMPT --> 2.5. 列出新库对象有效而源库失效对象
PROMPT    -------------------------------------------------
  select owner,object_name,object_type  from dba_objects where owner NOT IN ('DBMON','GOLDENGATE','PRECISE2','PRECISE1','SPATIAL_WFS_ADMIN_USR','DIP','MDDATA','ORACLE_OCM'
                      ,'SPATIAL_CSW_ADMIN_USR','XS$NULL','SCOTT','DBSNMP','SPA','OLAPSYS','ORDPLUGINS','XDB','SYSMAN'
                      ,'APPQOSSYS','DMSYS','EXFSYS','ORDSYS','SI_INFORMTN_SCHEMA','ANONYMOUS','CTXSYS','ORDDATA'
                      ,'WMSYS','MDSYS','SYSTEM','MGMT_VIEW','SYS','PUBLIC','OUTLN','TSMSYS','DSG','PERFSTAT','IGNITE_M') and STATUS='VALID'
  minus
  select owner,object_name,object_type  from dba_objects@TEST_COMPARE where owner NOT IN ('DBMON','GOLDENGATE','PRECISE2','PRECISE1','SPATIAL_WFS_ADMIN_USR','DIP','MDDATA','ORACLE_OCM'
                      ,'SPATIAL_CSW_ADMIN_USR','XS$NULL','SCOTT','DBSNMP','SPA','OLAPSYS','ORDPLUGINS','XDB','SYSMAN'
                      ,'APPQOSSYS','DMSYS','EXFSYS','ORDSYS','SI_INFORMTN_SCHEMA','ANONYMOUS','CTXSYS','ORDDATA'
                      ,'WMSYS','MDSYS','SYSTEM','MGMT_VIEW','SYS','PUBLIC','OUTLN','TSMSYS','DSG','PERFSTAT','IGNITE_M') and STATUS='VALID';


-- PROMPT --> 2.6. 列出源库对象失效新环境有效的对象
-- PROMPT    -------------------------------------------------
-- col object_name for a50
--   select owner,object_name,object_type  from dba_objects@TEST_COMPARE where owner NOT IN ('DBMON','GOLDENGATE','PRECISE2','PRECISE1','SPATIAL_WFS_ADMIN_USR','DIP','MDDATA','ORACLE_OCM'
--                       ,'SPATIAL_CSW_ADMIN_USR','XS$NULL','SCOTT','DBSNMP','SPA','OLAPSYS','ORDPLUGINS','XDB','SYSMAN'
--                       ,'APPQOSSYS','DMSYS','EXFSYS','ORDSYS','SI_INFORMTN_SCHEMA','ANONYMOUS','CTXSYS','ORDDATA'
--                       ,'WMSYS','MDSYS','SYSTEM','MGMT_VIEW','SYS','PUBLIC','OUTLN','TSMSYS','DSG','PERFSTAT','IGNITE_M') and STATUS='INVALID'
--   minus
--   select owner,object_name,object_type  from dba_objects where owner NOT IN ('DBMON','GOLDENGATE','PRECISE2','PRECISE1','SPATIAL_WFS_ADMIN_USR','DIP','MDDATA','ORACLE_OCM'
--                       ,'SPATIAL_CSW_ADMIN_USR','XS$NULL','SCOTT','DBSNMP','SPA','OLAPSYS','ORDPLUGINS','XDB','SYSMAN'
--                       ,'APPQOSSYS','DMSYS','EXFSYS','ORDSYS','SI_INFORMTN_SCHEMA','ANONYMOUS','CTXSYS','ORDDATA'
--                       ,'WMSYS','MDSYS','SYSTEM','MGMT_VIEW','SYS','PUBLIC','OUTLN','TSMSYS','DSG','PERFSTAT','IGNITE_M') and STATUS='INVALID';



PROMPT ====================================================
PROMPT 3. 检查数据库约束 ...
PROMPT ====================================================
PROMPT --> 3.1. 对比约束数量

SELECT OWNER, TYPE P_TYPE, MAX(P_CNT) P_CNT, MAX(O_CNT) O_CNT, MAX(P_CNT) - MAX(O_CNT) PO_DIFF
  FROM (SELECT OWNER, CONSTRAINT_TYPE TYPE, COUNT(*) P_CNT, 0 O_CNT
          FROM (SELECT CC.OWNER, CC.TABLE_NAME, CC.COLUMN_NAME, CO.CONSTRAINT_TYPE
                  FROM DBA_CONS_COLUMNS CC, DBA_CONSTRAINTS CO
                 WHERE CC.OWNER = CO.OWNER
                   AND CC.TABLE_NAME = CO.TABLE_NAME
                   AND CC.CONSTRAINT_NAME = CO.CONSTRAINT_NAME
                   AND CC.TABLE_NAME NOT LIKE 'BIN%'
                 UNION
                SELECT CC.OWNER, CC.TABLE_NAME, CC.COLUMN_NAME, 'C'
                  FROM DBA_CONS_COLUMNS CC, DBA_CONSTRAINTS CO
                 WHERE CC.OWNER = CO.OWNER
                   AND CC.TABLE_NAME = CO.TABLE_NAME
                   AND CC.CONSTRAINT_NAME = CO.CONSTRAINT_NAME
                   AND CC.TABLE_NAME NOT LIKE 'BIN%'
                   AND CO.CONSTRAINT_TYPE = 'P')
         GROUP BY OWNER, CONSTRAINT_TYPE
         UNION ALL
        SELECT OWNER, CONSTRAINT_TYPE, 0, COUNT(*)
          FROM (SELECT CC.OWNER, CC.TABLE_NAME, CC.COLUMN_NAME, CO.CONSTRAINT_TYPE
                  FROM DBA_CONS_COLUMNS@TEST_COMPARE CC, DBA_CONSTRAINTS@TEST_COMPARE CO
                 WHERE CC.OWNER = CO.OWNER
                   AND CC.TABLE_NAME = CO.TABLE_NAME
                   AND CC.CONSTRAINT_NAME = CO.CONSTRAINT_NAME
                   AND CC.TABLE_NAME NOT LIKE 'BIN%'
                 UNION
                SELECT CC.OWNER, CC.TABLE_NAME, CC.COLUMN_NAME, 'C'
                  FROM DBA_CONS_COLUMNS@TEST_COMPARE CC, DBA_CONSTRAINTS@TEST_COMPARE CO
                 WHERE CC.OWNER = CO.OWNER
                   AND CC.TABLE_NAME = CO.TABLE_NAME
                   AND CC.CONSTRAINT_NAME = CO.CONSTRAINT_NAME
                   AND CC.TABLE_NAME NOT LIKE 'BIN%'
                   AND CO.CONSTRAINT_TYPE = 'P')
         GROUP BY OWNER, CONSTRAINT_TYPE) C
 WHERE C.OWNER NOT IN ('DBMON','PRECISE2','PRECISE1','SPATIAL_WFS_ADMIN_USR','DIP','MDDATA','ORACLE_OCM'
                      ,'SPATIAL_CSW_ADMIN_USR','XS$NULL','SCOTT','DBSNMP','SPA','OLAPSYS','ORDPLUGINS','XDB','SYSMAN'
                      ,'APPQOSSYS','DMSYS','EXFSYS','ORDSYS','SI_INFORMTN_SCHEMA','ANONYMOUS','CTXSYS','ORDDATA'
                      ,'WMSYS','MDSYS','SYSTEM','MGMT_VIEW','SYS','PUBLIC','OUTLN','TSMSYS','DSG','PERFSTAT','IGNITE_M')
 GROUP BY OWNER, TYPE
HAVING MAX(P_CNT) <> MAX(O_CNT)
 ORDER BY PO_DIFF;

PROMPT --> 3.2. 列出生产库中比新库中多的约束
PROMPT    -------------------------------------------------

SELECT *
  FROM (SELECT CC.OWNER, CC.TABLE_NAME, CC.COLUMN_NAME, CO.CONSTRAINT_TYPE
          FROM DBA_CONS_COLUMNS CC, DBA_CONSTRAINTS CO
         WHERE CC.OWNER = CO.OWNER
           AND CC.CONSTRAINT_NAME = CO.CONSTRAINT_NAME
           AND CC.TABLE_NAME NOT LIKE 'BIN%'
         UNION
        SELECT CC.OWNER, CC.TABLE_NAME, CC.COLUMN_NAME, 'C'
          FROM DBA_CONS_COLUMNS CC, DBA_CONSTRAINTS CO
         WHERE CC.OWNER = CO.OWNER
           AND CC.CONSTRAINT_NAME = CO.CONSTRAINT_NAME
           AND CO.CONSTRAINT_TYPE = 'P')
 WHERE OWNER NOT IN ('DBMON','GOLDENGATE','PRECISE2','PRECISE1','SPATIAL_WFS_ADMIN_USR','DIP','MDDATA','ORACLE_OCM'
                    ,'SPATIAL_CSW_ADMIN_USR','XS$NULL','SCOTT','DBSNMP','SPA','OLAPSYS','ORDPLUGINS','XDB','SYSMAN'
                    ,'APPQOSSYS','DMSYS','EXFSYS','ORDSYS','SI_INFORMTN_SCHEMA','ANONYMOUS','CTXSYS','ORDDATA','WMSYS'
                    ,'MDSYS','SYSTEM','MGMT_VIEW','SYS','PUBLIC','OUTLN','TSMSYS','DSG','PERFSTAT','IGNITE_M')
MINUS
SELECT *
  FROM (SELECT CC.OWNER, CC.TABLE_NAME, CC.COLUMN_NAME, CO.CONSTRAINT_TYPE
          FROM DBA_CONS_COLUMNS@TEST_COMPARE CC, DBA_CONSTRAINTS@TEST_COMPARE CO
         WHERE CC.OWNER = CO.OWNER
           AND CC.CONSTRAINT_NAME = CO.CONSTRAINT_NAME
           AND CC.TABLE_NAME NOT LIKE 'BIN%'
         UNION
        SELECT CC.OWNER, CC.TABLE_NAME, CC.COLUMN_NAME, 'C'
          FROM DBA_CONS_COLUMNS@TEST_COMPARE CC, DBA_CONSTRAINTS@TEST_COMPARE CO
         WHERE CC.OWNER = CO.OWNER
           AND CC.CONSTRAINT_NAME = CO.CONSTRAINT_NAME
           AND CO.CONSTRAINT_TYPE = 'P')
 WHERE OWNER NOT IN ('DBMON','GOLDENGATE','PRECISE2','PRECISE1','SPATIAL_WFS_ADMIN_USR','DIP','MDDATA','ORACLE_OCM'
                    ,'SPATIAL_CSW_ADMIN_USR','XS$NULL','SCOTT','DBSNMP','SPA','OLAPSYS','ORDPLUGINS','XDB','SYSMAN'
                    ,'APPQOSSYS','DMSYS','EXFSYS','ORDSYS','SI_INFORMTN_SCHEMA','ANONYMOUS','CTXSYS','ORDDATA','WMSYS'
                    ,'MDSYS','SYSTEM','MGMT_VIEW','SYS','PUBLIC','OUTLN','TSMSYS','DSG','PERFSTAT','IGNITE_M');

PROMPT --> 3.3. 列出新库中比生产库中多的约束
PROMPT    -------------------------------------------------

SELECT *
  FROM (SELECT CC.OWNER, CC.TABLE_NAME, CC.COLUMN_NAME, CO.CONSTRAINT_TYPE
          FROM DBA_CONS_COLUMNS@TEST_COMPARE CC, DBA_CONSTRAINTS@TEST_COMPARE CO
         WHERE CC.OWNER = CO.OWNER
           AND CC.CONSTRAINT_NAME = CO.CONSTRAINT_NAME
           AND CC.TABLE_NAME NOT LIKE 'BIN%'
         UNION
        SELECT CC.OWNER, CC.TABLE_NAME, CC.COLUMN_NAME, 'C'
          FROM DBA_CONS_COLUMNS@TEST_COMPARE CC, DBA_CONSTRAINTS@TEST_COMPARE CO
         WHERE CC.OWNER = CO.OWNER
           AND CC.CONSTRAINT_NAME = CO.CONSTRAINT_NAME
           AND CO.CONSTRAINT_TYPE = 'P')
 WHERE OWNER NOT IN ('DBMON','GOLDENGATE','PRECISE2','PRECISE1','SPATIAL_WFS_ADMIN_USR','DIP','MDDATA','ORACLE_OCM'
                    ,'SPATIAL_CSW_ADMIN_USR','XS$NULL','SCOTT','DBSNMP','SPA','OLAPSYS','ORDPLUGINS','XDB','SYSMAN'
                    ,'APPQOSSYS','DMSYS','EXFSYS','ORDSYS','SI_INFORMTN_SCHEMA','ANONYMOUS','CTXSYS','ORDDATA','WMSYS'
                    ,'MDSYS','SYSTEM','MGMT_VIEW','SYS','PUBLIC','OUTLN','TSMSYS','DSG','PERFSTAT','IGNITE_M')
 MINUS
SELECT *
  FROM (SELECT CC.OWNER, CC.TABLE_NAME, CC.COLUMN_NAME, CO.CONSTRAINT_TYPE
          FROM DBA_CONS_COLUMNS CC, DBA_CONSTRAINTS CO
         WHERE CC.OWNER = CO.OWNER
           AND CC.CONSTRAINT_NAME = CO.CONSTRAINT_NAME
           AND CC.TABLE_NAME NOT LIKE 'BIN%'
         UNION
        SELECT CC.OWNER, CC.TABLE_NAME, CC.COLUMN_NAME, 'C'
          FROM DBA_CONS_COLUMNS CC, DBA_CONSTRAINTS CO
         WHERE CC.OWNER = CO.OWNER
           AND CC.CONSTRAINT_NAME = CO.CONSTRAINT_NAME
           AND CO.CONSTRAINT_TYPE = 'P')
 WHERE OWNER NOT IN ('DBMON','GOLDENGATE','PRECISE2','PRECISE1','SPATIAL_WFS_ADMIN_USR','DIP','MDDATA','ORACLE_OCM'
                    ,'SPATIAL_CSW_ADMIN_USR','XS$NULL','SCOTT','DBSNMP','SPA','OLAPSYS','ORDPLUGINS','XDB','SYSMAN'
                    ,'APPQOSSYS','DMSYS','EXFSYS','ORDSYS','SI_INFORMTN_SCHEMA','ANONYMOUS','CTXSYS','ORDDATA','WMSYS'
                    ,'MDSYS','SYSTEM','MGMT_VIEW','SYS','PUBLIC','OUTLN','TSMSYS','DSG','PERFSTAT','IGNITE_M');

PROMPT ====================================================
PROMPT 4. 检查数据库表列的定义 ...
PROMPT ====================================================
PROMPT --> 4.1. 列出生产库中比新库中多的数据表列
PROMPT    -------------------------------------------------

SELECT OWNER, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, DATA_DEFAULT
  FROM SPA.TAB_COLUMNS_O
MINUS
SELECT OWNER, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, DATA_DEFAULT
  FROM SPA.TAB_COLUMNS_N@TEST_COMPARE;

PROMPT --> 4.2. 列出新库中比生产库中多的数据表列
PROMPT    -------------------------------------------------

SELECT OWNER, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, DATA_DEFAULT
  FROM SPA.TAB_COLUMNS_N@TEST_COMPARE
MINUS
SELECT OWNER, TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, DATA_DEFAULT
  FROM SPA.TAB_COLUMNS_O;


PROMPT ====================================================
PROMPT 5. 检查数据库同义词 ...
PROMPT ====================================================
PROMPT --> 5.1. 对比同义词数量

SELECT OWNER, TABLE_OWNER, MAX(P_CNT) P_CNT, MAX(O_CNT) O_CNT, MAX(P_CNT) - MAX(O_CNT) PO_DIFF
  FROM (SELECT OWNER, NVL(TABLE_OWNER, OWNER) TABLE_OWNER, COUNT(*) P_CNT, 0 O_CNT
          FROM DBA_SYNONYMS
         GROUP BY OWNER, NVL(TABLE_OWNER, OWNER)
         UNION ALL
        SELECT OWNER, NVL(TABLE_OWNER, OWNER) TABLE_OWNER, 0, COUNT(*)
          FROM DBA_SYNONYMS@TEST_COMPARE
         GROUP BY OWNER, NVL(TABLE_OWNER, OWNER)) O
 WHERE O.TABLE_OWNER NOT IN ('DBMON','GOLDENGATE','PRECISE2','PRECISE1','SPATIAL_WFS_ADMIN_USR','DIP','MDDATA','ORACLE_OCM'
                            ,'SPATIAL_CSW_ADMIN_USR','XS$NULL','SCOTT','DBSNMP','SPA','OLAPSYS','ORDPLUGINS','XDB','SYSMAN'
                            ,'APPQOSSYS','DMSYS','EXFSYS','ORDSYS','SI_INFORMTN_SCHEMA','ANONYMOUS','CTXSYS','ORDDATA'
                            ,'WMSYS','MDSYS','SYSTEM','MGMT_VIEW','SYS','PUBLIC','OUTLN','TSMSYS','DSG','PERFSTAT','IGNITE_M')
 GROUP BY OWNER, TABLE_OWNER
HAVING MAX(P_CNT) <> MAX(O_CNT)
 ORDER BY PO_DIFF;

PROMPT --> 5.2. 列出生产库中比新库中多的同义词
PROMPT    -------------------------------------------------

SELECT *
  FROM (SELECT OWNER, SYNONYM_NAME, NVL(TABLE_OWNER, OWNER) TABLE_OWNER, TABLE_NAME, DB_LINK FROM DBA_SYNONYMS)
 WHERE TABLE_OWNER NOT IN ('DBMON','GOLDENGATE','PRECISE2','PRECISE1','SPATIAL_WFS_ADMIN_USR','DIP','MDDATA','ORACLE_OCM'
                          ,'SPATIAL_CSW_ADMIN_USR','XS$NULL','SCOTT','DBSNMP','SPA','OLAPSYS','ORDPLUGINS','XDB','SYSMAN'
                          ,'APPQOSSYS','DMSYS','EXFSYS','ORDSYS','SI_INFORMTN_SCHEMA','ANONYMOUS','CTXSYS','ORDDATA'
                          ,'WMSYS','MDSYS','SYSTEM','MGMT_VIEW','SYS','PUBLIC','OUTLN','TSMSYS','DSG','PERFSTAT','IGNITE_M')
MINUS
SELECT *
  FROM (SELECT OWNER, SYNONYM_NAME, NVL(TABLE_OWNER, OWNER) TABLE_OWNER, TABLE_NAME, DB_LINK FROM DBA_SYNONYMS@TEST_COMPARE)
 WHERE TABLE_OWNER NOT IN ('DBMON','GOLDENGATE','PRECISE2','PRECISE1','SPATIAL_WFS_ADMIN_USR','DIP','MDDATA','ORACLE_OCM'
                          ,'SPATIAL_CSW_ADMIN_USR','XS$NULL','SCOTT','DBSNMP','SPA','OLAPSYS','ORDPLUGINS','XDB','SYSMAN'
                          ,'APPQOSSYS','DMSYS','EXFSYS','ORDSYS','SI_INFORMTN_SCHEMA','ANONYMOUS','CTXSYS','ORDDATA'
                          ,'WMSYS','MDSYS','SYSTEM','MGMT_VIEW','SYS','PUBLIC','OUTLN','TSMSYS','DSG','PERFSTAT','IGNITE_M');

PROMPT --> 5.3. 列出新库中比生产库中多的同义词
PROMPT    -------------------------------------------------

SELECT *
  FROM (SELECT OWNER, SYNONYM_NAME, NVL(TABLE_OWNER, OWNER) TABLE_OWNER, TABLE_NAME, DB_LINK FROM DBA_SYNONYMS@TEST_COMPARE)
 WHERE TABLE_OWNER NOT IN ('DBMON','GOLDENGATE','PRECISE2','PRECISE1','SPATIAL_WFS_ADMIN_USR','DIP','MDDATA','ORACLE_OCM'
                          ,'SPATIAL_CSW_ADMIN_USR','XS$NULL','SCOTT','DBSNMP','SPA','OLAPSYS','ORDPLUGINS','XDB','SYSMAN'
                          ,'APPQOSSYS','DMSYS','EXFSYS','ORDSYS','SI_INFORMTN_SCHEMA','ANONYMOUS','CTXSYS','ORDDATA'
                          ,'WMSYS','MDSYS','SYSTEM','MGMT_VIEW','SYS','PUBLIC','OUTLN','TSMSYS','DSG','PERFSTAT','IGNITE_M')
MINUS
SELECT *
  FROM (SELECT OWNER, SYNONYM_NAME, NVL(TABLE_OWNER, OWNER) TABLE_OWNER, TABLE_NAME, DB_LINK FROM DBA_SYNONYMS)
 WHERE TABLE_OWNER NOT IN ('DBMON','GOLDENGATE','PRECISE2','PRECISE1','SPATIAL_WFS_ADMIN_USR','DIP','MDDATA','ORACLE_OCM'
                          ,'SPATIAL_CSW_ADMIN_USR','XS$NULL','SCOTT','DBSNMP','SPA','OLAPSYS','ORDPLUGINS','XDB','SYSMAN'
                          ,'APPQOSSYS','DMSYS','EXFSYS','ORDSYS','SI_INFORMTN_SCHEMA','ANONYMOUS','CTXSYS','ORDDATA'
                          ,'WMSYS','MDSYS','SYSTEM','MGMT_VIEW','SYS','PUBLIC','OUTLN','TSMSYS','DSG','PERFSTAT','IGNITE_M');

SPO OFF
PROMPT 检查数据库对象结束，请检查当前目录中的【checkObject.txt】文件
EXIT
