CREATE OR REPLACE TRIGGER "SYS"."ADG_LOGON_RECOVER_TRIGGER"
   AFTER STARTUP
   ON DATABASE
BEGIN
   IF (SYS_CONTEXT ('USERENV', 'DATABASE_ROLE') IN ('PHYSICAL STANDBY'))
   THEN
      EXECUTE IMMEDIATE
         'ALTER DATABASE RECOVER MANAGED STANDBY DATABASE USING CURRENT LOGFILE disconnect';
   END IF;
END;