SET LONG 20000 LONGCHUNKSIZE 20000 PAGESIZE 0 LINESIZE 1000 FEEDBACK OFF VERIFY OFF TRIMSPOOL ON
COLUMN ddl FORMAT a1000

BEGIN
   DBMS_METADATA.set_transform_param (DBMS_METADATA.session_transform,
                                      'SQLTERMINATOR',
                                      TRUE);
   DBMS_METADATA.set_transform_param (DBMS_METADATA.session_transform,
                                      'PRETTY',
                                      TRUE);
END;
/


SELECT DBMS_METADATA.get_ddl ('ROLE', r.role) AS ddl
  FROM dba_roles r
 WHERE r.role NOT IN
          ('ADM_PARALLEL_EXECUTE_TASK',
           'APEX_ADMINISTRATOR_ROLE',
           'AQ_ADMINISTRATOR_ROLE',
           'AQ_USER_ROLE',
           'AUTHENTICATEDUSER',
           'CONNECT',
           'CSW_USR_ROLE',
           'CTXAPP',
           'CWM_USER',
           'DATAPUMP_EXP_FULL_DATABASE',
           'DATAPUMP_IMP_FULL_DATABASE',
           'DBA',
           'DBFS_ROLE',
           'DELETE_CATALOG_ROLE',
           'EJBCLIENT',
           'EXECUTE_CATALOG_ROLE',
           'EXP_FULL_DATABASE',
           'GATHER_SYSTEM_STATISTICS',
           'GLOBAL_AQ_USER_ROLE',
           'HS_ADMIN_EXECUTE_ROLE',
           'HS_ADMIN_ROLE',
           'HS_ADMIN_SELECT_ROLE',
           'IMP_FULL_DATABASE',
           'JAVADEBUGPRIV',
           'JAVAIDPRIV',
           'JAVASYSPRIV',
           'JAVAUSERPRIV',
           'JAVA_ADMIN',
           'JAVA_DEPLOY',
           'JMXSERVER',
           'LOGSTDBY_ADMINISTRATOR',
           'MGMT_USER',
           'OEM_ADVISOR',
           'OEM_MONITOR',
           'OLAP_DBA',
           'OLAP_USER',
           'OLAP_XS_ADMIN',
           'ORDADMIN',
           'OWB$CLIENT',
           'OWB_DESIGNCENTER_VIEW',
           'OWB_USER',
           'RECOVERY_CATALOG_OWNER',
           'RESOURCE',
           'SCHEDULER_ADMIN',
           'SELECT_CATALOG_ROLE',
           'SPATIAL_CSW_ADMIN',
           'SPATIAL_WFS_ADMIN',
           'WFS_USR_ROLE',
           'WM_ADMIN_ROLE',
           'XDBADMIN',
           'XDB_SET_INVOKER',
           'XDB_WEBSERVICES',
           'XDB_WEBSERVICES_OVER_HTTP',
           'XDB_WEBSERVICES_WITH_PUBLIC')
UNION ALL
SELECT DBMS_METADATA.get_granted_ddl ('ROLE_GRANT', grantee) AS ddl
  FROM (SELECT DISTINCT grantee grantee
          FROM dba_role_privs rp
         WHERE rp.grantee  IN
                  (SELECT r.role
                     FROM dba_roles r
                    WHERE r.role NOT IN
                             ('ADM_PARALLEL_EXECUTE_TASK',
                              'APEX_ADMINISTRATOR_ROLE',
                              'AQ_ADMINISTRATOR_ROLE',
                              'AQ_USER_ROLE',
                              'AUTHENTICATEDUSER',
                              'CONNECT',
                              'CSW_USR_ROLE',
                              'CTXAPP',
                              'CWM_USER',
                              'DATAPUMP_EXP_FULL_DATABASE',
                              'DATAPUMP_IMP_FULL_DATABASE',
                              'DBA',
                              'DBFS_ROLE',
                              'DELETE_CATALOG_ROLE',
                              'EJBCLIENT',
                              'EXECUTE_CATALOG_ROLE',
                              'EXP_FULL_DATABASE',
                              'GATHER_SYSTEM_STATISTICS',
                              'GLOBAL_AQ_USER_ROLE',
                              'HS_ADMIN_EXECUTE_ROLE',
                              'HS_ADMIN_ROLE',
                              'HS_ADMIN_SELECT_ROLE',
                              'IMP_FULL_DATABASE',
                              'JAVADEBUGPRIV',
                              'JAVAIDPRIV',
                              'JAVASYSPRIV',
                              'JAVAUSERPRIV',
                              'JAVA_ADMIN',
                              'JAVA_DEPLOY',
                              'JMXSERVER',
                              'LOGSTDBY_ADMINISTRATOR',
                              'MGMT_USER',
                              'OEM_ADVISOR',
                              'OEM_MONITOR',
                              'OLAP_DBA',
                              'OLAP_USER',
                              'OLAP_XS_ADMIN',
                              'ORDADMIN',
                              'OWB$CLIENT',
                              'OWB_DESIGNCENTER_VIEW',
                              'OWB_USER',
                              'RECOVERY_CATALOG_OWNER',
                              'RESOURCE',
                              'SCHEDULER_ADMIN',
                              'SELECT_CATALOG_ROLE',
                              'SPATIAL_CSW_ADMIN',
                              'SPATIAL_WFS_ADMIN',
                              'WFS_USR_ROLE',
                              'WM_ADMIN_ROLE',
                              'XDBADMIN',
                              'XDB_SET_INVOKER',
                              'XDB_WEBSERVICES',
                              'XDB_WEBSERVICES_OVER_HTTP',
                              'XDB_WEBSERVICES_WITH_PUBLIC')))
UNION ALL
SELECT DBMS_METADATA.get_granted_ddl ('SYSTEM_GRANT', grantee) AS ddl
  FROM (SELECT DISTINCT grantee grantee
          FROM dba_sys_privs sp
         WHERE sp.grantee  IN
                  (SELECT r.role
                     FROM dba_roles r
                    WHERE r.role NOT IN
                             ('ADM_PARALLEL_EXECUTE_TASK',
                              'APEX_ADMINISTRATOR_ROLE',
                              'AQ_ADMINISTRATOR_ROLE',
                              'AQ_USER_ROLE',
                              'AUTHENTICATEDUSER',
                              'CONNECT',
                              'CSW_USR_ROLE',
                              'CTXAPP',
                              'CWM_USER',
                              'DATAPUMP_EXP_FULL_DATABASE',
                              'DATAPUMP_IMP_FULL_DATABASE',
                              'DBA',
                              'DBFS_ROLE',
                              'DELETE_CATALOG_ROLE',
                              'EJBCLIENT',
                              'EXECUTE_CATALOG_ROLE',
                              'EXP_FULL_DATABASE',
                              'GATHER_SYSTEM_STATISTICS',
                              'GLOBAL_AQ_USER_ROLE',
                              'HS_ADMIN_EXECUTE_ROLE',
                              'HS_ADMIN_ROLE',
                              'HS_ADMIN_SELECT_ROLE',
                              'IMP_FULL_DATABASE',
                              'JAVADEBUGPRIV',
                              'JAVAIDPRIV',
                              'JAVASYSPRIV',
                              'JAVAUSERPRIV',
                              'JAVA_ADMIN',
                              'JAVA_DEPLOY',
                              'JMXSERVER',
                              'LOGSTDBY_ADMINISTRATOR',
                              'MGMT_USER',
                              'OEM_ADVISOR',
                              'OEM_MONITOR',
                              'OLAP_DBA',
                              'OLAP_USER',
                              'OLAP_XS_ADMIN',
                              'ORDADMIN',
                              'OWB$CLIENT',
                              'OWB_DESIGNCENTER_VIEW',
                              'OWB_USER',
                              'RECOVERY_CATALOG_OWNER',
                              'RESOURCE',
                              'SCHEDULER_ADMIN',
                              'SELECT_CATALOG_ROLE',
                              'SPATIAL_CSW_ADMIN',
                              'SPATIAL_WFS_ADMIN',
                              'WFS_USR_ROLE',
                              'WM_ADMIN_ROLE',
                              'XDBADMIN',
                              'XDB_SET_INVOKER',
                              'XDB_WEBSERVICES',
                              'XDB_WEBSERVICES_OVER_HTTP',
                              'XDB_WEBSERVICES_WITH_PUBLIC')))
UNION ALL
SELECT DBMS_METADATA.get_granted_ddl ('OBJECT_GRANT', grantee) AS ddl
  FROM (SELECT DISTINCT grantee grantee
          FROM dba_tab_privs tp
         WHERE tp.grantee  IN
                  (SELECT r.role
                     FROM dba_roles r
                    WHERE r.role NOT IN
                             ('ADM_PARALLEL_EXECUTE_TASK',
                              'APEX_ADMINISTRATOR_ROLE',
                              'AQ_ADMINISTRATOR_ROLE',
                              'AQ_USER_ROLE',
                              'AUTHENTICATEDUSER',
                              'CONNECT',
                              'CSW_USR_ROLE',
                              'CTXAPP',
                              'CWM_USER',
                              'DATAPUMP_EXP_FULL_DATABASE',
                              'DATAPUMP_IMP_FULL_DATABASE',
                              'DBA',
                              'DBFS_ROLE',
                              'DELETE_CATALOG_ROLE',
                              'EJBCLIENT',
                              'EXECUTE_CATALOG_ROLE',
                              'EXP_FULL_DATABASE',
                              'GATHER_SYSTEM_STATISTICS',
                              'GLOBAL_AQ_USER_ROLE',
                              'HS_ADMIN_EXECUTE_ROLE',
                              'HS_ADMIN_ROLE',
                              'HS_ADMIN_SELECT_ROLE',
                              'IMP_FULL_DATABASE',
                              'JAVADEBUGPRIV',
                              'JAVAIDPRIV',
                              'JAVASYSPRIV',
                              'JAVAUSERPRIV',
                              'JAVA_ADMIN',
                              'JAVA_DEPLOY',
                              'JMXSERVER',
                              'LOGSTDBY_ADMINISTRATOR',
                              'MGMT_USER',
                              'OEM_ADVISOR',
                              'OEM_MONITOR',
                              'OLAP_DBA',
                              'OLAP_USER',
                              'OLAP_XS_ADMIN',
                              'ORDADMIN',
                              'OWB$CLIENT',
                              'OWB_DESIGNCENTER_VIEW',
                              'OWB_USER',
                              'RECOVERY_CATALOG_OWNER',
                              'RESOURCE',
                              'SCHEDULER_ADMIN',
                              'SELECT_CATALOG_ROLE',
                              'SPATIAL_CSW_ADMIN',
                              'SPATIAL_WFS_ADMIN',
                              'WFS_USR_ROLE',
                              'WM_ADMIN_ROLE',
                              'XDBADMIN',
                              'XDB_SET_INVOKER',
                              'XDB_WEBSERVICES',
                              'XDB_WEBSERVICES_OVER_HTTP',
                              'XDB_WEBSERVICES_WITH_PUBLIC')))
/

SET LINESIZE 80 PAGESIZE 14 FEEDBACK ON VERIFY ON