SET LONG 1000000
SET LONGCHUNKSIZE 1000000
SET VERIFY OFF
SET LINESIZE 1000
SET PAGESIZE 0
SET TRIM ON
SET TRIMSPOOL ON
SET ECHO OFF
SET FEEDBACK OFF
col report for a200
undefine reportid;
SELECT DBMS_AUTO_REPORT.REPORT_REPOSITORY_DETAIL(RID => '&reportid', TYPE => 'TEXT')
  FROM DUAL;

undefine reportid;