set echo off
set lines 2000 pages 4000 verify off heading on
set timing on
@db_advisor_task_by_sqlpa.sql

PROMP   "****[TEST] EXECUTE - test-execute every SQL statement and collect its execution plans and execution statistics.               ***"
PROMP   "****                The resulting plans and statistics will be stored in the advisor framework. This is default.              ***"
PROMP   "****EXPLAIN PLAN - generate explain plan for every statement in the SQL workload. This is similar to the EXPLAIN PLAN command.***"
PROMP   "****                The resulting plans will be stored in the advisor framework in association with the task.                 ***"
PROMP   "****COMPARE [PERFORMANCE] - analyze and compare two versions of SQL performance data. The performance data is generated by    ***"
PROMP   "****                        test-executing or generating explain plan of the SQL statements. Use this option when             ***"
PROMP   "****                        two executions of type EXPLAIN_PLAN or TEST_EXECUTE already exist in the task                     ***"
PROMP   "****CONVERT SQLSET - used to read the statistics captured in a SQL Tuning Set and model them as a task execution.             ***"
PROMP   "****                This can be used when you wish to avoid executing the SQL statements because valid data                   ***"
PROMP   "****                for the experiment already exists in the SQL Tuning Set.                                                  ***"

DECLARE
   v_task_name          VARCHAR2 (1000);
   v_execution_type     VARCHAR2 (1000);
   v_execution_name     VARCHAR2 (1000);
   v_execution_params   DBMS_ADVISOR.argList;
   v_execution_desc     VARCHAR2 (1000);
BEGIN
   v_task_name := '&task_name';
   v_execution_type := NVL (UPPER ('&execution_type'), 'TEST EXECUTE');
   v_execution_name := NVL ('&execution_name', NULL);
   v_execution_desc := NVL ('&execution_desc', NULL);

   DBMS_SQLPA.EXECUTE_ANALYSIS_TASK (task_name          => v_task_name,
                                     execution_type     => v_execution_type,
                                     execution_name     => v_execution_name,
                                     execution_params   => NULL,
                                     execution_desc     => v_execution_desc);
END;
/